// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/FloatingPhotoPortfolio-EWdd7M/FloatingGallery.tsx": () => import("../components/mockups/templates/FloatingPhotoPortfolio-EWdd7M/FloatingGallery.tsx")
};
